Update producer.py
groupbwt/scrapy-boilerplate pull request #50
Opened 2020-08-04 11:58 UTC by Nevoliashka

fix producer, rework updating rows

2020-08-31 15:05 UTC, KristobalJunta requested changes

2020-08-31 15:05 UTC, KristobalJunta commented on src/rmq/commands/producer.py
> +         deferreds = []
Тут ошибка отступа

2020-08-31 15:05 UTC, KristobalJunta commented on src/rmq/commands/producer.py
> +            deferreds.append(deferred_update_row)
В строках 275-280 и 282-288 я вижу два куска кода, которые выглядят почти одинаково, только второй использует deferred.
Уточни, пожалуйста, дважды одно и то же с виду действие делается целенаправленно, либо второй кусок должен заменить первый, а не быть рядом с ним?

2020-09-02 07:06 UTC, Nevoliashka commented on src/rmq/commands/producer.py
> +            deferreds.append(deferred_update_row)
Видимо как-то каряво слилось. Первого цикла быть не должно.

2020-09-16 13:13 UTC, KristobalJunta approved these changes

2020-09-16 13:34 UTC, merged